#
# SPDX-FileCopyrightText: 2025 Jens A. Koch
# SPDX-License-Identifier: MIT
#
# This file is part of https://github.com/jakoch/simpletest-docs-ui
#

name: Publish to GitHub Pages

on:
  # You can manually run this workflow.
  workflow_dispatch:
  # This workflow does run when pushing to the main branch.
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:

# ---------------------------------------------------------------------------------------

  publish:

# ---------------------------------------------------------------------------------------

    name: "Publish to gh-pages"
    runs-on: ubuntu-latest

    concurrency:
      group: pages
      cancel-in-progress: true

    steps:
      - name: ðŸ¤˜ Checkout main branch
        uses: actions/checkout@v5 # https://github.com/actions/checkout

      - name: ðŸ”½ Setup Node.js
        uses: actions/setup-node@v5 # https://github.com/actions/setup-node
        with:
          node-version: '20'

      - name: ðŸ”½ Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: ðŸ”½ Install dependencies
        run: npm ci --legacy-peer-deps

      - name: Build assets (this stages assets (css,js,fonts,etc) into public/_)
        run: |
          npx gulp build

      - name: Verify generated assets
        run: |
          ls -lahr public/_/
          test -f public/_/css/site.css || (echo "ERROR: missing public/_/css/site.css" && exit 1)
          test -f public/_/js/site.js  || (echo "ERROR: missing public/_/js/site.js" && exit 1)
          test -d public/_/font        || (echo "ERROR: missing public/_/font" && exit 1)

      - name: ðŸ”¨ Build preview (this stages into public/)"
        run: |
          npx gulp preview:build

      - name: Verify generated preview site
        run: |
          ls -lahr public/
          test -f public/index.html || (echo "ERROR: missing public/index.html" && exit 1)

      - name: Create zip (build/ui-bundle.zip)
        run: |
          npx gulp bundle

      # Upload the UI bundle as an artifact (useable as Antora UI bundle)
      - name: Upload UI bundle as artifact
        uses: actions/upload-artifact@v4 # https://github.com/actions/upload-artifact
        with:
          name: ui-bundle
          path: build/ui-bundle.zip

      # Publish the `public` folder to GitHub Pages (UI demo site)
      - name: ðŸ“¦ Upload `public` folder for Pages
        uses: actions/upload-pages-artifact@v4 # https://github.com/actions/upload-pages-artifact
        with:
          path: public

      - name: ðŸš€ Deploy to GitHub Pages
        uses: actions/deploy-pages@v4 # https://github.com/actions/deploy-pages
